name = "score-kort"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "score-kort-db"
database_id = "32df5e07-9ddb-4358-bbb9-fe7a9396c3d8"
